table Dim_Calendario
	lineageTag: 6aad96b2-026a-4971-9160-30aa725640f7

	measure 'Total Ventas' = COUNTROWS(Fact_Ventas)
		formatString: 0
		lineageTag: 9b0efea5-d7d1-4c5f-ab57-70b6e01a7e4e

	measure 'Total Ingresos' = ```
			SUM(Fact_Ventas[Precio Venta sin IGV])
			
			```
		lineageTag: 94550dc5-8402-4bbd-9a67-380a85ddbf06

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ticket Promedio' = ```
			DIVIDE([Total Ingresos], [Total Ventas])
			
			```
		lineageTag: 834f2e49-3ea7-479c-8b0c-512573799d77

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Costo Total' = ```
			SUM(Fact_Ventas[Costo Vehículo])
			
			```
		lineageTag: 1d7b8405-3816-4b30-bae6-425bcf54a323

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: f8bb4659-294c-4ae8-99ed-f04e2da3062b
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: c4a4b932-477a-4fe5-be60-73f120d3d0cf
			defaultHierarchy: LocalDateTable_ac0f1b38-4ab0-4fa3-9267-52e664cd8755.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 73c4956e-66e4-4159-a48a-ae24b07e2171
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Semana
		dataType: int64
		formatString: 0
		lineageTag: bec96938-9972-4629-940b-d7e8babc3a68
		summarizeBy: sum
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 95feb27d-f967-4707-a165-8a63b564ffe8
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Numero Mes'
		dataType: int64
		formatString: 0
		lineageTag: 4fc48dc3-07a5-43bd-8a9e-c701a88c67a2
		summarizeBy: sum
		sourceColumn: Numero Mes

		annotation SummarizationSetBy = Automatic

	column datekey
		dataType: int64
		formatString: 0
		lineageTag: 3f05a281-a3ea-4cfb-bd8c-b48978d38147
		summarizeBy: none
		sourceColumn: datekey

		annotation SummarizationSetBy = Automatic

	partition Dim_Calendario = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\vaned\Downloads\VentasVehiculos.xlsx"), null, true),
				    Dim_Calendario_Table = Origen{[Item="Dim_Calendario",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Dim_Calendario_Table,{{"Fecha", type date}, {"Año", Int64.Type}, {"Semana", Int64.Type}, {"Mes", type text}, {"Numero Mes", Int64.Type}, {"datekey", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

