table dim_sede
	lineageTag: d37bffd6-955b-470f-9616-db0da9e38183

	column id_sede
		dataType: int64
		formatString: 0
		lineageTag: 911c5ef2-ff00-407d-bb41-35ed473a5fc7
		summarizeBy: none
		sourceColumn: id_sede

		annotation SummarizationSetBy = Automatic

	column nombre_sede
		dataType: string
		lineageTag: a7e816c8-9b4a-400b-94e5-7fce89a53b21
		summarizeBy: none
		sourceColumn: nombre_sede

		annotation SummarizationSetBy = Automatic

	column ubicacion_sede
		dataType: string
		lineageTag: 807786a7-a050-4f92-bc36-4f6a2a864521
		summarizeBy: none
		sourceColumn: ubicacion_sede

		annotation SummarizationSetBy = Automatic

	partition dim_sede = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\vaned\Downloads\VentasVehiculos.xlsx"), null, true),
				    dim_sede_Table = Origen{[Item="dim_sede",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(dim_sede_Table,{{"id_sede", Int64.Type}, {"nombre_sede", type text}, {"ubicacion_sede", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

