table dim_vehiculo
	lineageTag: 5ed33afe-7c0b-403f-800a-2fa26bc9bb46

	column id_vehiculo
		dataType: int64
		formatString: 0
		lineageTag: 73b4773a-13c1-4d99-a652-00fd54de8674
		summarizeBy: none
		sourceColumn: id_vehiculo

		annotation SummarizationSetBy = Automatic

	column marca_vehiculo
		dataType: string
		lineageTag: 46caaf63-2b6e-465d-a8c4-ce7bc99545ac
		summarizeBy: none
		sourceColumn: marca_vehiculo

		annotation SummarizationSetBy = Automatic

	column modelo_vehiculo
		dataType: string
		lineageTag: 2d27e050-1256-4c18-87ae-b645a5e7ccd3
		summarizeBy: none
		sourceColumn: modelo_vehiculo

		annotation SummarizationSetBy = Automatic

	column tipo_vehiculo
		dataType: string
		lineageTag: 02a04f08-aad5-46da-96f1-cbd152377785
		summarizeBy: none
		sourceColumn: tipo_vehiculo

		annotation SummarizationSetBy = Automatic

	column a침o_vehiculo
		dataType: int64
		formatString: 0
		lineageTag: 3c9f7089-a5ba-4714-926e-26c4a9745d87
		summarizeBy: none
		sourceColumn: a침o_vehiculo

		annotation SummarizationSetBy = Automatic

	partition dim_vehiculo = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\vaned\Downloads\VentasVehiculos.xlsx"), null, true),
				    dim_vehiculo_Table = Origen{[Item="dim_vehiculo",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(dim_vehiculo_Table,{{"id_vehiculo", Int64.Type}, {"marca_vehiculo", type text}, {"modelo_vehiculo", type text}, {"tipo_vehiculo", type text}, {"a침o_vehiculo", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegaci칩n

	annotation PBI_ResultType = Table

